/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package sae.View.jDialog;

import java.util.Calendar;
import java.util.Date;
import javax.swing.JSpinner;
import javax.swing.SpinnerDateModel;

/**
 *
 * @author fillo
 */
public class GivenHourDialog extends javax.swing.JDialog {

    /**
     * Creates new form GivenHourDialog
     */
    public GivenHourDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        initHours();
        setLocationRelativeTo(null);
    }

    private void initHours() {
        Date date = new Date();

        SpinnerDateModel smStart = new SpinnerDateModel(date, null, null, Calendar.HOUR_OF_DAY);
        spinnerStartHour.setModel(smStart);

        Calendar calendar = Calendar.getInstance();
        calendar.setTime(date);
        calendar.add(Calendar.HOUR_OF_DAY, 2);
        Date endDate = calendar.getTime();

        SpinnerDateModel smEnd = new SpinnerDateModel(endDate, null, null, Calendar.HOUR_OF_DAY);
        spinnerEndHour.setModel(smEnd);

        JSpinner.DateEditor dateEditorStart = new JSpinner.DateEditor(spinnerStartHour, "HH:mm:ss");
        JSpinner.DateEditor dateEditorEnd = new JSpinner.DateEditor(spinnerEndHour, "HH:mm:ss");

        spinnerStartHour.setEditor(dateEditorStart);
        spinnerEndHour.setEditor(dateEditorEnd);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        labelTitle = new javax.swing.JLabel();
        spinnerStartHour = new javax.swing.JSpinner();
        spinnerEndHour = new javax.swing.JSpinner();
        separator = new javax.swing.JSeparator();
        labelEndHour = new javax.swing.JLabel();
        labelStartHour = new javax.swing.JLabel();
        jOkayButton = new javax.swing.JButton();
        jCancelButton = new javax.swing.JButton();

        jButton1.setText("jButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        labelTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelTitle.setText("Veuillez sélectionner un intervalle d'heures");

        spinnerStartHour.setMaximumSize(new java.awt.Dimension(40, 20));
        spinnerStartHour.setMinimumSize(new java.awt.Dimension(40, 20));
        spinnerStartHour.setPreferredSize(new java.awt.Dimension(40, 20));

        spinnerEndHour.setMaximumSize(new java.awt.Dimension(40, 20));
        spinnerEndHour.setMinimumSize(new java.awt.Dimension(40, 20));
        spinnerEndHour.setPreferredSize(new java.awt.Dimension(40, 20));

        labelEndHour.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelEndHour.setText("Heure fin");

        labelStartHour.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelStartHour.setText("Heure début");

        jOkayButton.setBackground(new java.awt.Color(235, 173, 59));
        jOkayButton.setForeground(new java.awt.Color(0, 0, 0));
        jOkayButton.setText("Ok");
        jOkayButton.setMaximumSize(new java.awt.Dimension(100, 25));
        jOkayButton.setMinimumSize(new java.awt.Dimension(100, 25));
        jOkayButton.setPreferredSize(new java.awt.Dimension(100, 25));
        jOkayButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jOkayButtonActionPerformed(evt);
            }
        });

        jCancelButton.setBackground(new java.awt.Color(235, 173, 59));
        jCancelButton.setForeground(new java.awt.Color(0, 0, 0));
        jCancelButton.setText("Annuler");
        jCancelButton.setMaximumSize(new java.awt.Dimension(100, 25));
        jCancelButton.setMinimumSize(new java.awt.Dimension(100, 25));
        jCancelButton.setPreferredSize(new java.awt.Dimension(100, 25));
        jCancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCancelButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(labelTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(separator, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(109, 109, 109))
            .addGroup(layout.createSequentialGroup()
                .addGap(74, 74, 74)
                .addComponent(jCancelButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45)
                .addComponent(jOkayButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(81, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(spinnerStartHour, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(labelStartHour, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(labelEndHour, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(spinnerEndHour, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(labelTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(separator, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(spinnerEndHour, javax.swing.GroupLayout.DEFAULT_SIZE, 26, Short.MAX_VALUE)
                    .addComponent(spinnerStartHour, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelEndHour)
                    .addComponent(labelStartHour))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCancelButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jOkayButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jOkayButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jOkayButtonActionPerformed

        this.dispose();
    }//GEN-LAST:event_jOkayButtonActionPerformed

    private void jCancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCancelButtonActionPerformed
        this.dispose();
    }//GEN-LAST:event_jCancelButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jCancelButton;
    private javax.swing.JButton jOkayButton;
    private javax.swing.JLabel labelEndHour;
    private javax.swing.JLabel labelStartHour;
    private javax.swing.JLabel labelTitle;
    private javax.swing.JSeparator separator;
    private javax.swing.JSpinner spinnerEndHour;
    private javax.swing.JSpinner spinnerStartHour;
    // End of variables declaration//GEN-END:variables
}
